### ISSUE TITLE
Is it possible to have consistent directory contents?

### ISSUE THREAD

**Issue by aspsk** [phatina/simple-mtpfs#27]
After a successful mount of my android device to my Linux host, I can add/remove files to/from it using the Linux host. Such changes are visible to the simple-mtpfs.

But when I am adding or removing a file on the android device itself, simple-mtpfs doesn't see it and displays the old directory contents.

Is it possible to tell to the simple-mtpfs to re-read directory contents on demand?

**Comment by Massimo-B** [comment]
The directory structure has changed on the device but simple-mtpfs still shows some old structure. That means md5sum on files there results in "Numerical result out of range".

I remounted the FS, I restarted the Android device, but it does not help. How can I force a refresh?
Anyway is it possible to mount the FS without that caching? I only use simple-mtpfs to synchronize a structure using unison.
