### ISSUE TITLE
include files prevent compile on OSX

### ISSUE THREAD

**Issue by risacher** [phatina/simple-mtpfs#30]
To get simple-mtp to compile on OS X "Mavericks" I had to add a flag in src/makefile to include /usr/local/include/oxsfuse.  (I'm using osxfuse and other libraries from http://brew.sh)

The line I modified is this:
FUSE_CFLAGS = -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/Cellar/osxfuse/2.6.2/include/osxfuse/fuse  -I/usr/local/include/osxfuse  

(When using homebrew, /usr/local/include/osxfuse is a symlink to /usr/local/Cellar/osxfuse/2.6.2/include/osxfuse)

The compile error is this:
simple-mtpfs-fuse.cpp:22:12: fatal error: 'fuse/fuse_opt.h' file not found

Since the makefile is generated by Autoconf, it's not obvious to me how to fix this upstream.

Alternatively, I can change 2 #include lines in simple-mtpfs-fuse.h and simple-mtpfs.fuse.cpp to drop the "fuse/" prefix, and that also resolves the issue (for me, anyway), but I'm not sure if that will break the build on Linux or other platforms.

**Comment by intuited** [comment]
Looks like this never got committed — I just checked out the repo and the lines that "are the problem" (as per [@mormy's comment](https://github.com/phatina/simple-mtpfs/issues/30#issuecomment-56362818) are still there.

I've changed the lines to what @mormy recommends and `make` now completes successfully.  I'm able to run `simple-mtpfs` but am getting an error when I try to mount that may be unrelated.

The change is in the `osx-include` branch of my fork: https://github.com/intuited/simple-mtpfs/tree/osx-include

I have no idea what effect these changes have when building on other platforms, so I can't make a pull request.

**Comment by phatina** [comment]
Hi,

can you, please verify this patch?  I would like to have this working with Linux/Mac OS X both.  I see, that running Fedora box, I can leave AC_SUBST() for FUSE and LIBUSB1 (they are both substituted in Makefiles).  And only if $os_name == "Darwin", we need to specify different paths, etc.

Thank you.

``` diff
diff --git a/configure.ac b/configure.ac
index ad45463..cf3e630 100644
--- a/configure.ac
+++ b/configure.ac
@@ -20,19 +20,20 @@ AC_CHECK_LIB([mtp], [LIBMTP_Check_Capability],
 AC_CHECK_HEADERS([libmtp.h])
 
 dnl Enable fdatasync, but not on OSX
-test `uname -s` == "Darwin" || AC_CHECK_FUNCS([fdatasync])
+os_name=$(uname -s)
+test "x$os_name" == "xDarwin" || AC_CHECK_FUNCS([fdatasync])
 
 PKG_CHECK_MODULES([FUSE], [fuse >= 2.7.3])
-AC_SUBST([FUSE_CFLAGS])
-AC_SUBST([FUSE_LIBS])
+if test "x$os_name" == "xDarwin"; then
+    AC_SUBST([FUSE_CFLAGS],["-D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -I/usr/local/opt/osxfuse/include/osxfuse"])
+    AC_SUBST([FUSE_LIBS],["-L/usr/local/opt/osxfuse//lib -losxfuse -pthread -liconv"])
+fi
 
 PKG_CHECK_MODULES(
     [LIBUSB1],
     [libusb-1.0 >= 1.0.0],
     [AC_DEFINE([HAVE_LIBUSB1], [], [Have libusb 1.0])]
 )
-AC_SUBST([LIBUSB1_CFLAGS])
-AC_SUBST([LIBUSB1_LIBS])
 
 dnl Configurable temporary directory
 AC_ARG_WITH(
```

**Comment by parashep** [comment]
Hi! It doesn't work, because those don't seem to be the correct locations. As of OS X Yosemite, osxfuse isn't built from source due to some new restrictions on unsigned kernel extensions. Homebrew now installs the binary, from [here](http://osxfuse.github.io). From what I gather, this is the reason why the file locations have changed.

the locations I found worked are:
FUSE_CFLAGS = /usr/local/include/osxfuse
FUSE_LIBS = /usr/local//lib

have yet to try usage, but substituting those into your patch, it builds and installs properly!

**Comment by phatina** [comment]
OK, so am I good to push the patch with your paths?

**Comment by parashep** [comment]
Looking good, yeah. It might not work with previous configurations of FUSE on OS X because the implementation seems to be a little all over the place, but it should work with the latest version of OSXFUSE.

**Comment by phatina** [comment]
Thanks for your help.  Pushed 7efc34b.
