### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by notramo** [phatina/simple-mtpfs#62]
This would make possible easily writing front-ends.

**Comment by GravisZro** [comment]
This is a crazy request because it completely defeats the purpose of FUSE.  You should close this ticket.

**Comment by phatina** [comment]
> This is a crazy request because it completely defeats the purpose of FUSE. You should close this ticket.

Agreed.

**Comment by notramo** [comment]
@phatina Why would it defeat the purpose of fuse? It has nothing to do with FUSE. I meant JSON output for e.g. device listing.
